
package ServicesTypes;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameService", targetNamespace = "http://Services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameService {


    /**
     * 
     * @return
     *     returns java.util.List<ServicesTypes.CardInfoPair>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeckList", targetNamespace = "http://Services/", className = "ServicesTypes.GetDeckList")
    @ResponseWrapper(localName = "getDeckListResponse", targetNamespace = "http://Services/", className = "ServicesTypes.GetDeckListResponse")
    @Action(input = "http://Services/GameService/getDeckListRequest", output = "http://Services/GameService/getDeckListResponse")
    public List<CardInfoPair> getDeckList();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "playCard", targetNamespace = "http://Services/", className = "ServicesTypes.PlayCard")
    @ResponseWrapper(localName = "playCardResponse", targetNamespace = "http://Services/", className = "ServicesTypes.PlayCardResponse")
    @Action(input = "http://Services/GameService/playCardRequest", output = "http://Services/GameService/playCardResponse")
    public void playCard(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns ServicesTypes.GameInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameState", targetNamespace = "http://Services/", className = "ServicesTypes.GetGameState")
    @ResponseWrapper(localName = "getGameStateResponse", targetNamespace = "http://Services/", className = "ServicesTypes.GetGameStateResponse")
    @Action(input = "http://Services/GameService/getGameStateRequest", output = "http://Services/GameService/getGameStateResponse")
    public GameInfo getGameState();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayerCards", targetNamespace = "http://Services/", className = "ServicesTypes.GetPlayerCards")
    @ResponseWrapper(localName = "getPlayerCardsResponse", targetNamespace = "http://Services/", className = "ServicesTypes.GetPlayerCardsResponse")
    @Action(input = "http://Services/GameService/getPlayerCardsRequest", output = "http://Services/GameService/getPlayerCardsResponse")
    public List<Integer> getPlayerCards();

    /**
     * 
     * @return
     *     returns ServicesTypes.BoardGraph
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGameBoardGraph", targetNamespace = "http://Services/", className = "ServicesTypes.GetGameBoardGraph")
    @ResponseWrapper(localName = "getGameBoardGraphResponse", targetNamespace = "http://Services/", className = "ServicesTypes.GetGameBoardGraphResponse")
    @Action(input = "http://Services/GameService/getGameBoardGraphRequest", output = "http://Services/GameService/getGameBoardGraphResponse")
    public BoardGraph getGameBoardGraph();

}
