
package Services;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExampleService", targetNamespace = "http://Controller/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExampleService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Hello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://Controller/", className = "Services.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://Controller/", className = "Services.HelloResponse")
    @Action(input = "http://Controller/ExampleService/HelloRequest", output = "http://Controller/ExampleService/HelloResponse")
    public String hello();

}
