
package Services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExampleServiceService", targetNamespace = "http://Controller/", wsdlLocation = "http://localhost:8080/Server_war_exploded/services/ExampleService?wsdl")
public class ExampleServiceService
    extends Service
{

    private final static URL EXAMPLESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXAMPLESERVICESERVICE_EXCEPTION;
    private final static QName EXAMPLESERVICESERVICE_QNAME = new QName("http://Controller/", "ExampleServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Server_war_exploded/services/ExampleService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMPLESERVICESERVICE_WSDL_LOCATION = url;
        EXAMPLESERVICESERVICE_EXCEPTION = e;
    }

    public ExampleServiceService() {
        super(__getWsdlLocation(), EXAMPLESERVICESERVICE_QNAME);
    }

    public ExampleServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMPLESERVICESERVICE_QNAME, features);
    }

    public ExampleServiceService(URL wsdlLocation) {
        super(wsdlLocation, EXAMPLESERVICESERVICE_QNAME);
    }

    public ExampleServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMPLESERVICESERVICE_QNAME, features);
    }

    public ExampleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleService getExampleServicePort() {
        return super.getPort(new QName("http://Controller/", "ExampleServicePort"), ExampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleService getExampleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controller/", "ExampleServicePort"), ExampleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMPLESERVICESERVICE_EXCEPTION!= null) {
            throw EXAMPLESERVICESERVICE_EXCEPTION;
        }
        return EXAMPLESERVICESERVICE_WSDL_LOCATION;
    }

}
