
package Services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GameServiceService", targetNamespace = "http://Controller/", wsdlLocation = "http://localhost:8080/Server_war_exploded/services/GameService?wsdl")
public class GameServiceService
    extends Service
{

    private final static URL GAMESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException GAMESERVICESERVICE_EXCEPTION;
    private final static QName GAMESERVICESERVICE_QNAME = new QName("http://Controller/", "GameServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Server_war_exploded/services/GameService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAMESERVICESERVICE_WSDL_LOCATION = url;
        GAMESERVICESERVICE_EXCEPTION = e;
    }

    public GameServiceService() {
        super(__getWsdlLocation(), GAMESERVICESERVICE_QNAME);
    }

    public GameServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAMESERVICESERVICE_QNAME, features);
    }

    public GameServiceService(URL wsdlLocation) {
        super(wsdlLocation, GAMESERVICESERVICE_QNAME);
    }

    public GameServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAMESERVICESERVICE_QNAME, features);
    }

    public GameServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GameServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GameService
     */
    @WebEndpoint(name = "GameServicePort")
    public GameService getGameServicePort() {
        return super.getPort(new QName("http://Controller/", "GameServicePort"), GameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GameService
     */
    @WebEndpoint(name = "GameServicePort")
    public GameService getGameServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controller/", "GameServicePort"), GameService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAMESERVICESERVICE_EXCEPTION!= null) {
            throw GAMESERVICESERVICE_EXCEPTION;
        }
        return GAMESERVICESERVICE_WSDL_LOCATION;
    }

}
