
package Services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameService", targetNamespace = "http://Controller/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameService {


    /**
     * 
     * @return
     *     returns java.util.List<Services.GameInfo>
     */
    @WebMethod(operationName = "GameList")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GameList", targetNamespace = "http://Controller/", className = "Services.GameList")
    @ResponseWrapper(localName = "GameListResponse", targetNamespace = "http://Controller/", className = "Services.GameListResponse")
    @Action(input = "http://Controller/GameService/GameListRequest", output = "http://Controller/GameService/GameListResponse")
    public List<GameInfo> gameList();

}
